---
- name: Create teleport service (systemd).
  template:
    src: "teleport.service.j2"
    dest: "/usr/lib/systemd/system/teleport.service"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_installed

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  become: yes
  when: service_installed.changed